export const NAV_LINKS = [
  { href: '#hero',       label: 'Home',       rune: '᛫' },
  { href: '#about',      label: 'About',      rune: 'ᚦ' },
  { href: '#projects',   label: 'Projects',   rune: 'ᚱ' },
  { href: '#skills',     label: 'Skills',     rune: 'ᛋ' },
  { href: '#experience', label: 'Experience', rune: 'ᛖ' },
  { href: '#contact',    label: 'Contact',    rune: 'ᚲ' },
]

export const PROJECTS = [
  {
    id: 'p1', cat: 'ai',
    emoji: '🎵',
    img: '/emotion-music.jpg',
    bg: 'linear-gradient(135deg,#0d0820,#1a0d35)',
    catLabel: 'AI / ML · Real-Time', date: 'Aug–Dec 2025',
    title: 'Emotion-Based Music Recommender',
    desc: 'Real-time facial emotion recognition → Spotify playlist generation. PyTorch + EfficientNet + two-tower embedding architecture.',
    tags: ['PyTorch','EfficientNet','OpenCV','Streamlit','Spotify API','Docker'],
    overview: 'End-to-end real-time system: webcam captures facial emotion, PyTorch model classifies it, and Spotify API generates a matching playlist instantly. Replaced naive rule-based mapping with a learned two-tower embedding architecture.',
    bullets: [
      'Built modular PyTorch pipeline using EfficientNet and Swin Transformer to improve FER2013 baseline emotion recognition',
      'Replaced rule-based mapping with two-tower embedding architecture for scalable contextual song matching',
      'Integrated Spotify API for real-time dynamic playlist generation based on detected emotional state',
      'Deployed Streamlit app with live webcam feed, per-class confidence visualization, and playlist controls',
      'Structured for extensibility: swappable backbone, feedback-driven ranking',
    ],
    tech: ['Python','PyTorch','EfficientNet','Swin Transformer','OpenCV','Pandas','Streamlit','Spotify API','Docker'],
  },
  {
    id: 'p2', cat: 'web',
    emoji: '📚',
    img: '/studybud.jpg',
    bg: 'linear-gradient(135deg,#050f1a,#0a1e35)',
    catLabel: 'Full-Stack · Cloud', date: 'Mar–May 2025',
    title: 'StudyBud — AI Collaborative Platform',
    desc: 'Cloud-native study platform with LLaMA AI assistant, JWT auth, Docker, and AWS ECS Fargate deployment.',
    tags: ['React','Node.js','MongoDB','AWS ECS','GROQ LLaMA','Docker'],
    overview: 'Cloud-native collaborative study platform with LLaMA AI assistant for contextual academic support. Deployed on AWS ECS Fargate with Docker containerization.',
    bullets: [
      'Architected Node.js + Express backend with JWT auth and role-based access control',
      'Designed MongoDB schemas for users, sessions, tasks with proper indexing',
      'Integrated GROQ Chat API (LLaMA models) for real-time AI study assistant responses',
      'Containerized with Docker and deployed to AWS ECS Fargate for scalable serverless execution',
      'Implemented middleware-based validation and structured error handling',
    ],
    tech: ['React','Node.js','Express','MongoDB','Docker','AWS ECS Fargate','GROQ LLaMA','JWT'],
  },
  {
    id: 'p3', cat: 'ai',
    emoji: '🛡️',
    img: '/malware.jpg',
    bg: 'linear-gradient(135deg,#081505,#0f2a0a)',
    catLabel: 'Deep Learning · Research', date: 'Mar–May 2025',
    title: 'Malware Detection via CNN Classification',
    desc: 'Binary-to-image pipeline classifying malware families using CNN deep learning. Evaluated VAE, GAN, Diffusion, WGAN-GP.',
    tags: ['Python','PyTorch','CNN','OpenCV','NumPy'],
    overview: 'Pipeline converting malware binary executables into grayscale image representations for CNN-based classification across malware families.',
    bullets: [
      'Designed pipeline converting binary files into 2D image representations for visual malware fingerprinting',
      'Implemented CNN architecture for image-based malware family classification',
      'Evaluated generative architectures (VAE, GAN, Diffusion, WGAN-GP) for augmenting imbalanced datasets',
      'Conducted ablation studies on preprocessing and architecture choices',
    ],
    tech: ['Python','PyTorch','CNN','Deep Learning','OpenCV','Pandas','NumPy','Scikit-learn'],
  },
  {
    id: 'p6', cat: 'ai',
    emoji: '🧠',
    img: '/emotion-inference.jpg',
    bg: 'linear-gradient(135deg,#150510,#200a0a)',
    catLabel: 'Computer Vision · Real-Time', date: 'Jan 2026–Present',
    title: 'Real-Time Emotion Inference System',
    desc: 'Live webcam inference with per-class confidence visualization. Modular Python architecture with separate layers.',
    tags: ['Python','PyTorch','OpenCV','Streamlit'],
    overview: 'Live inference system processing continuous webcam frames through a PyTorch emotion classifier with per-class confidence visualization in Streamlit.',
    bullets: [
      'Built real-time inference pipeline processing webcam frames at interactive frame rates',
      'Designed modular Python architecture: separate data ingestion, model inference, UI rendering',
      'Implemented Streamlit visualization with live per-class confidence scores and state transitions',
      'Engineered for minimal end-to-end latency with performance monitoring built in',
    ],
    tech: ['Python','PyTorch','OpenCV','Streamlit','NumPy','Computer Vision'],
  },
  {
    id: 'p4', cat: 'ios',
    emoji: '📱',
    img: '/dailyquotes.jpg',
    bg: 'linear-gradient(135deg,#1a0510,#300a20)',
    catLabel: 'iOS · Swift', date: '2022',
    title: 'DailyQuotes — Native iOS App',
    desc: 'Native iOS app with MVC architecture, CoreData persistence, and optimized 60fps UITableView rendering.',
    tags: ['Swift','UIKit','CoreData','MVC','Xcode'],
    overview: 'Native iOS app delivering daily inspirational quotes with CoreData persistence, local favorites, and smooth 60fps animations — built with clean MVC architecture.',
    bullets: [
      'Built with MVC architecture for clean separation of concerns',
      'CoreData + UserDefaults for quotes and preference persistence',
      'Optimized UITableView with cell reuse, lazy loading for 60fps',
      'Custom cells with swipe-to-favorite and share interactions',
    ],
    tech: ['Swift','UIKit','CoreData','UserDefaults','MVC','Xcode','TestFlight'],
  },
  {
    id: 'p5', cat: 'iot',
    emoji: '🛒',
    img: '/smartcart.jpg',
    bg: 'linear-gradient(135deg,#151005,#252010)',
    catLabel: 'IoT · Embedded Systems', date: '2021–2022',
    title: 'Intelligent Shopping Cart',
    desc: 'RFID + Zigbee IoT system with real-time item tracking, automated billing, and contactless payment checkout.',
    tags: ['RFID','Zigbee','Wi-Fi','Embedded C','Raspberry Pi'],
    overview: 'Hardware-software smart cart using RFID and Zigbee for real-time item tracking, automated billing, and contactless payment — eliminating traditional checkout.',
    bullets: [
      'RFID + Zigbee item detection for real-time product identification',
      'Automated billing engine computing totals as customers shop',
      'Contactless payment workflow integrated with payment gateway',
      'Embedded firmware for RFID readers with Wi-Fi cloud sync',
    ],
    tech: ['RFID','Zigbee','Wi-Fi','Embedded C','IoT','Payment Gateway','Raspberry Pi'],
  },
]

export const SKILLS = [
  { n:'Swift',       cat:'ios',   lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg' },
  { n:'SwiftUI',     cat:'ios',   lvl:'master', ico:'🐦' },
  { n:'UIKit',       cat:'ios',   lvl:'master', ico:'📱' },
  { n:'WKWebView',   cat:'ios',   lvl:'master', ico:'🌐' },
  { n:'Xcode',       cat:'ios',   lvl:'master', ico:'🛠️' },
  { n:'Objective-C', cat:'ios',   lvl:'app',    ico:'©️' },
  { n:'Python',      cat:'web',   lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
  { n:'React',       cat:'web',   lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  { n:'Node.js',     cat:'web',   lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
  { n:'Express',     cat:'web',   lvl:'adept',  ico:'⚙️' },
  { n:'REST APIs',   cat:'web',   lvl:'master', ico:'🔌' },
  { n:'JWT Auth',    cat:'web',   lvl:'adept',  ico:'🔐' },
  { n:'PyTorch',     cat:'ai',    lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg' },
  { n:'OpenCV',      cat:'ai',    lvl:'adept',  ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg' },
  { n:'EfficientNet',cat:'ai',    lvl:'adept',  ico:'🧬' },
  { n:'LLaMA/GROQ',  cat:'ai',    lvl:'adept',  ico:'🤖' },
  { n:'CNN',         cat:'ai',    lvl:'adept',  ico:'🧠' },
  { n:'Streamlit',   cat:'ai',    lvl:'adept',  ico:'🎨' },
  { n:'AWS ECS',     cat:'cloud', lvl:'adept',  ico:'☁️' },
  { n:'Docker',      cat:'cloud', lvl:'master', ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  { n:'Jenkins',     cat:'cloud', lvl:'adept',  ico:'🔧' },
  { n:'Firebase',    cat:'cloud', lvl:'adept',  ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
  { n:'Kibana',      cat:'cloud', lvl:'adept',  ico:'📊' },
  { n:'CI/CD',       cat:'cloud', lvl:'adept',  ico:'⚡' },
  { n:'MySQL',       cat:'data',  lvl:'adept',  ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
  { n:'MongoDB',     cat:'data',  lvl:'adept',  ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  { n:'Pandas',      cat:'data',  lvl:'adept',  ico:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
  { n:'CoreData',    cat:'data',  lvl:'adept',  ico:'💾' },
  { n:'SQL Design',  cat:'data',  lvl:'adept',  ico:'📐' },
]

export const MARQUEE_ROW1 = [
  { n:'Swift',   src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg' },
  { n:'Python',  src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
  { n:'React',   src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  { n:'Node.js', src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
  { n:'Docker',  src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  { n:'PyTorch', src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg' },
  { n:'Git',     src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
  { n:'Figma',   src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg' },
]

export const MARQUEE_ROW2 = [
  { n:'MongoDB', src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  { n:'MySQL',   src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
  { n:'OpenCV',  src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg' },
  { n:'Firebase',src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
  { n:'Pandas',  src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
  { n:'AWS',     src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg' },
  { n:'Jenkins', src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg' },
  { n:'Xcode',   src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xcode/xcode-original.svg' },
]

export const EXPERIENCE = [
  {
    id: 'e1',
    logo: '/entain.png',
    role: 'Software Engineer',
    company: 'Entain',
    period: 'Aug 2023 – Jul 2024',
    location: 'Hyderabad, India · iOS / Swift / WKWebView',
    bullets: [
      { text: 'Engineered embedded Casino integration within Poker iOS app for BETMGM, Borgata, Coral, and Ladbrokes using Swift, UIKit, WKWebView, and REST APIs', impact: 'Thousands of daily users' },
      { text: 'Reduced game launch latency by ~30 seconds and app size by ~30MB via WebView lifecycle optimization and strategic asset loading', impact: '~30s faster' },
      { text: 'Re-architected game launch routing — intercepted and validated URLs inside WKWebView delegate, built CasinoAPI wrapper eliminating production crashes', impact: null },
      { text: 'Built custom SessionManager enforcing responsible gaming: session token injection, duplicate detection, strict termination', impact: 'Regulatory compliance' },
      { text: 'Diagnosed crashes via Firebase Crashlytics + Kibana log correlation. Managed CI/CD across Jenkins, AppCenter, TestFlight', impact: null },
    ],
  },
  {
    id: 'e2',
    logo: '/entain.png',
    role: 'Trainee Software Engineer',
    company: 'Entain',
    period: 'Jul 2022 – Aug 2023',
    location: 'Hyderabad, India · macOS / iOS / Firebase',
    bullets: [
      { text: 'Resolved complex UI rendering defects in macOS Poker client — reduced repeat defect tickets', impact: '~20–25% reduction' },
      { text: 'Migrated legacy logging to Firebase Analytics + Crashlytics, reducing debug turnaround', impact: '~30% faster' },
      { text: 'Integrated REST-based wallet and transaction services without App Store redeployment', impact: '30+ apps' },
      { text: 'Monitored live production via Kibana dashboards — traced distributed session and API issues', impact: null },
    ],
  },
  {
    id: 'e3',
    logo: '/epam.png',
    role: 'Junior Software Engineer',
    company: 'EPAM Systems',
    period: 'Jan 2022 – Jul 2022',
    location: 'Hyderabad, India · Full-Stack / Python / MySQL',
    bullets: [
      { text: 'Built full-stack quiz platform with RESTful APIs, normalized MySQL schema, and JWT-based auth for secure multi-user delivery', impact: null },
      { text: 'Optimized SQL queries — improved backend response under concurrent load', impact: '~25–30% faster' },
      { text: 'Implemented validation, duplicate submission prevention, middleware error handling', impact: '~15% fewer errors' },
    ],
  },
]

export const TIMELINE = [
  { year: '2024–Present', title: 'M.S. Computer Science', org: 'San Jose State University · CA', detail: 'ML, Cloud Computing, Distributed Systems, NoSQL, Parallel Processing. Expected May 2026.', color: '#c8a84a' },
  { year: 'Aug 2023–Jul 2024', title: 'Software Engineer', org: 'Entain · Hyderabad, India', detail: 'Casino iOS integration, ~30s latency reduction, CI/CD for 4 major brands.', color: '#e8566a' },
  { year: 'Jul 2022–Aug 2023', title: 'Trainee Software Engineer', org: 'Entain · Hyderabad', detail: 'macOS/iOS dev, Firebase migration, wallet APIs across 30+ apps.', color: '#20b8a8' },
  { year: 'Jan 2022–Jul 2022', title: 'Junior Software Engineer', org: 'EPAM Systems · Hyderabad', detail: 'Full-stack quiz platform: REST APIs, JWT auth, MySQL schemas.', color: '#2860a8' },
  { year: '2018–2022', title: 'B.Tech Computer Science', org: 'MLR Institute of Technology · Hyderabad', detail: 'Core CS. Head of Promotions at SCOPE — hackathons for 200+ students.', color: '#e4c870' },
]

export const SOFT_SKILLS = {
  afterHero: [
    { ico: '🧭', name: 'Leadership', desc: 'As Chapter President of Kontagious at SJSU, I lead community-building initiatives for 100+ international students — from airport pickups to career mentorship.' },
    { ico: '🤝', name: 'Cross-Functional Collaboration', desc: 'At Entain I worked daily with product, design, and backend teams to align multi-brand iOS releases across BETMGM, Borgata, Coral, and Ladbrokes.' },
    { ico: '⚡', name: 'Ownership & Delivery', desc: 'I own features end-to-end — from reading a Figma spec to shipping through TestFlight — without waiting to be told what to do next.' },
  ],
  afterProjects: [
    { ico: '🔍', name: 'Problem Solving', desc: 'I diagnosed production crash root causes by correlating Firebase Crashlytics reports with Kibana log traces across distributed Poker and Casino services.' },
    { ico: '📐', name: 'Attention to Detail', desc: 'By independently investigating layout edge cases in the macOS Poker client, I reduced repeat UI defect tickets by approximately 20–25%.' },
    { ico: '🔐', name: 'Regulatory Awareness', desc: 'I built a SessionManager that enforced responsible gaming limits — detecting duplicate backend sessions and ensuring strict termination for compliance.' },
  ],
  afterSkills: [
    { ico: '📣', name: 'Public Speaking', desc: 'As Head of Promotions at SCOPE, I presented at club events and organised technical competitions for 200+ students including Modifest and GameHub hackathons.' },
    { ico: '🏆', name: 'Hackathons & Competitions', desc: 'I organised and ran coding contests, hackathons, and workshops that brought students together around engineering challenges and collaborative problem-solving.' },
    { ico: '💬', name: 'Clear Communication', desc: 'I communicated root-cause findings to backend stakeholders at Entain, turning complex distributed-system incidents into clear, actionable resolution steps.' },
  ],
  afterTimeline: [
    { ico: '🎯', name: 'Goal-Oriented Execution', desc: 'I delivered Casino feature integration across four major brands — BETMGM, Borgata, Coral, and Ladbrokes — cutting game launch latency by ~30 seconds end-to-end.' },
    { ico: '🌱', name: 'Continuous Learning', desc: 'I am currently pursuing an MS in Computer Science at SJSU, deepening expertise in ML, Cloud Computing, and Distributed Systems alongside active engineering work.' },
    { ico: '🌍', name: 'Mentorship & Community', desc: 'Through Kontagious I coordinate airport pickups, welcome luncheons, and career guidance sessions — building real community for students navigating a new country.' },
  ],
}

export const LEADERSHIP = [
  {
    icon: '🌍',
    role: 'Chapter President',
    org: 'Kontagious · San José State University',
    date: 'May 2025 – May 2026',
    desc: 'Led a nonprofit chapter building inclusive community for international students — airport pickups, welcome luncheons, career guidance, mentorship programs, and cross-cultural networking events at SJSU.',
    tags: ['Leadership','Community Building','Mentorship','Event Organization'],
  },
  {
    icon: '💻',
    role: 'Head of Promotions',
    org: 'SCOPE – School of Programming & Excellence · MLR Institute',
    date: 'Apr 2020 – Mar 2022',
    desc: 'Organized workshops and hackathons for 200+ students including Modifest, GameHub, and coding contests. Supervised promotions across network channels and presented at club events.',
    tags: ['Hackathons','Event Organizing','Public Speaking','200+ Students'],
  },
]

export const TRAIT_CHIPS = [
  '🧭 Leadership','📣 Public Speaking','🏆 Hackathons',
  '🤝 Collaboration','⚡ Agile / Scrum','🌍 Mentorship',
  '🔍 Problem Solving','📐 Attention to Detail',
]
